import { resolve } from "node:path";
function numberEnv(name: string, fallback: number) {
    const value = Number(process.env[name]);
    return Number.isFinite(value) && value > 0 ? value : fallback;
}
export const WORKSPACE_ROOT = resolve(process.env["WORKSPACE_ROOT"] || "./workspace-sessions");
export const WORKSPACE_METADATA_PATH = resolve(process.env["WORKSPACE_METADATA_PATH"] || `${WORKSPACE_ROOT}/.registry/workspaces.json`);
export const OPERATION_METADATA_PATH = resolve(process.env["OPERATION_METADATA_PATH"] || `${WORKSPACE_ROOT}/.registry/operations.json`);
export const CAPACITY_LEDGER_PATH = resolve(process.env["CAPACITY_LEDGER_PATH"] || `${WORKSPACE_ROOT}/.registry/capacity.json`);
const backendInstanceId = process.env["BACKEND_INSTANCE_ID"]?.trim() || "sk-coder";
export const BACKEND_INSTANCE_ID = /^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,62}$/.test(backendInstanceId) ? backendInstanceId : "sk-coder";
export const RUNTIME_IMAGE = process.env["RUNTIME_IMAGE"] || "sk-coder-runtime:latest";
export const GUI_RUNTIME_IMAGE = process.env["GUI_RUNTIME_IMAGE"] || "sk-coder-gui:latest";
export const APK_RUNTIME_IMAGE = process.env["APK_RUNTIME_IMAGE"] || "sk-coder-apk:latest";
export const SESSION_TTL_HOURS = numberEnv("SESSION_TTL_HOURS", 72);
export const SESSION_MAX_BYTES = numberEnv("SESSION_MAX_BYTES", 5 * 1024 * 1024 * 1024);
export const WORKSPACE_INITIAL_RESERVATION_BYTES = numberEnv("WORKSPACE_INITIAL_RESERVATION_BYTES", 1024 * 1024);
export const WORKSPACE_INSTALL_RESERVE_BYTES = numberEnv("WORKSPACE_INSTALL_RESERVE_BYTES", 512 * 1024 * 1024);
export const WORKSPACE_MAX_BYTES = numberEnv("WORKSPACE_MAX_BYTES", 50 * 1024 * 1024 * 1024);
export const SHARED_POOL_MAX_BYTES = numberEnv("SHARED_POOL_MAX_BYTES", WORKSPACE_MAX_BYTES);
export const SHARED_POOL_ADMISSION_BYTES = Math.min(numberEnv("SHARED_POOL_ADMISSION_BYTES", 48 * 1024 * 1024 * 1024), SHARED_POOL_MAX_BYTES);
export const RUNNER_SCRATCH_MAX_BYTES = numberEnv("RUNNER_SCRATCH_MAX_BYTES", 35 * 1024 * 1024 * 1024);
export const STAGING_MAX_BYTES = numberEnv("STAGING_MAX_BYTES", 15 * 1024 * 1024 * 1024);
export const RUNTIME_CACHE_MAX_BYTES = numberEnv("RUNTIME_CACHE_MAX_BYTES", 25 * 1024 * 1024 * 1024);
export const WORKSPACE_SAFETY_RESERVE_BYTES = numberEnv("WORKSPACE_SAFETY_RESERVE_BYTES", 25 * 1024 * 1024 * 1024);
export const PACKAGE_CACHE_MAX_BYTES = numberEnv("PACKAGE_CACHE_MAX_BYTES", 20 * 1024 * 1024 * 1024);
export const PACKAGE_CACHE_ROOT = resolve(process.env["PACKAGE_CACHE_ROOT"] || `${WORKSPACE_ROOT}/.cache/packages`);
export const LOG_MAX_BYTES = numberEnv("LOG_MAX_BYTES", 5 * 1024 * 1024 * 1024);
export const HOST_MEMORY_RESERVE_BYTES = numberEnv("HOST_MEMORY_RESERVE_BYTES", 2 * 1024 * 1024 * 1024);
export const HOST_LOAD_MAX = numberEnv("HOST_LOAD_MAX", 3);
export const SESSION_MAX_COUNT = numberEnv("SESSION_MAX_COUNT", 50);
export const SESSION_IDLE_MINUTES = numberEnv("SESSION_IDLE_MINUTES", 30);
export const RUNNER_MAX_COUNT = numberEnv("RUNNER_MAX_COUNT", 2);
export const RUNNER_QUEUE_MAX_COUNT = numberEnv("RUNNER_QUEUE_MAX_COUNT", 20);
export const COMMAND_TIMEOUT_MS = numberEnv("COMMAND_TIMEOUT_MS", 120000);
export const OUTPUT_MAX_BYTES = numberEnv("OUTPUT_MAX_BYTES", 500000);
export const WORKSPACE_NETWORK_MODE = process.env["WORKSPACE_NETWORK_MODE"] === "bridge" ? "bridge" : "none";
export const DEPENDENCY_INSTALL_NETWORK_MODE = process.env["DEPENDENCY_INSTALL_NETWORK_MODE"] === "bridge" ? "bridge" : "none";
export const DEPENDENCY_INSTALL_PROXY_URL = process.env["DEPENDENCY_INSTALL_PROXY_URL"]?.trim() || "";
const installerNetworkName = process.env["DEPENDENCY_INSTALL_NETWORK_NAME"]?.trim() || "skcoder-installer";
export const DEPENDENCY_INSTALL_NETWORK_NAME = /^[a-zA-Z0-9][a-zA-Z0-9_.-]{0,62}$/.test(installerNetworkName) ? installerNetworkName : "skcoder-installer";
export const DEPENDENCY_INSTALL_TIMEOUT_MS = numberEnv("DEPENDENCY_INSTALL_TIMEOUT_MS", 180000);
export const GUI_SESSION_MAX_COUNT = numberEnv("GUI_SESSION_MAX_COUNT", 1);
export const GUI_SESSION_TTL_MS = numberEnv("GUI_SESSION_TTL_MS", 10 * 60 * 1000);
export const GUI_SESSION_MEMORY_MB = numberEnv("GUI_SESSION_MEMORY_MB", 1024);
export const PREVIEW_RUNTIME_IMAGE = process.env["PREVIEW_RUNTIME_IMAGE"] || RUNTIME_IMAGE;
export const PREVIEW_SESSION_MAX_COUNT = numberEnv("PREVIEW_SESSION_MAX_COUNT", 1);
export const PREVIEW_SESSION_TTL_MS = numberEnv("PREVIEW_SESSION_TTL_MS", 15 * 60 * 1000);
export const PREVIEW_SESSION_MEMORY_MB = numberEnv("PREVIEW_SESSION_MEMORY_MB", 1024);
export const APK_JOB_MAX_COUNT = numberEnv("APK_JOB_MAX_COUNT", 1);
export const APK_JOB_MEMORY_MB = numberEnv("APK_JOB_MEMORY_MB", 1536);
export const APK_JOB_TIMEOUT_MS = numberEnv("APK_JOB_TIMEOUT_MS", 180000);
export const APK_JOB_TTL_MS = numberEnv("APK_JOB_TTL_MS", 30 * 60 * 1000);
export const APK_JOB_MIN_RESERVATION_BYTES = numberEnv("APK_JOB_MIN_RESERVATION_BYTES", 64 * 1024 * 1024);
export const APK_JOB_EXPANSION_MULTIPLIER = numberEnv("APK_JOB_EXPANSION_MULTIPLIER", 8);
